name: pylint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pylint_check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: Install dependencies
      run: python -m pip install --upgrade pip setuptools pylint pylint-exit

    - name: Run Pylint Checks
      run: pylint --rcfile=.pylintrc $(find . -iname "*.py") || pylint-exit --error-fail $?
