name: pylint

env:
  interpreted_pylint: |
    function fail_on_fatal_or_error_only() {
      # We care about fatal (1) and error (2) messages only.
      # The exit code is a sum of numbers corresponding to the message severity level.
      # E.g. if there are both error (2) and warning (4) messages, the exit code is 6.
      local exit_code=0
      pylint --rcfile=.pylintrc ./ || exit_code=$?
      if ! [ $((exit_code & 3)) -eq 0 ]; then
        return $exit_code;
      fi;
      return 0;
    }
    fail_on_fatal_or_error_only

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:        
  pylint_check:
    runs-on: ubuntu-latest
    container: centos:centos7.7.1908

    steps:
    - uses: actions/checkout@v1

    - name: Install Requirements
      run: |
        yum --enablerepo=extras install -y epel-release
        yum install -y python-pip
        pip install --upgrade pip
        pip install setuptools
        pip install pylint

    - name: Run Pylint Checks
      run: ${{ env.interpreted_pylint }}
