name: pylint

env:
  interpreted_pylint: |
    function fail_on_fatal_or_error_only() {
      # We care about fatal (1) and error (2) messages only.
      # The exit code is a sum of numbers corresponding to the message severity level.
      # E.g. if there are both error (2) and warning (4) messages, the exit code is 6.
      local exit_code=0
      find . -iname "*.py" | xargs pylint --rcfile=.pylintrc || exit_code=$?
      if ! [ $((exit_code & 3)) -eq 0 ]; then
        return $exit_code;
      fi;
      return 0;
    }
    fail_on_fatal_or_error_only

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pylint_check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: Install dependencies
      run: python -m pip install --upgrade pip setuptools pylint

    - name: Run Pylint Checks
      run: ${{ env.interpreted_pylint }}
